"""empty message

Revision ID: 1540a12d86c3
Revises: 373926e8e642
Create Date: 2022-12-07 02:39:35.751434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1540a12d86c3'
down_revision = '373926e8e642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'dataset_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('dataset_file', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
