"""empty message

Revision ID: 373926e8e642
Revises: befea11f8642
Create Date: 2022-12-06 05:55:37.643163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '373926e8e642'
down_revision = 'befea11f8642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'dataset_file',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'dataset_file',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
