"""empty message

Revision ID: befea11f8642
Revises: 24d769a75e44
Create Date: 2022-12-06 03:18:52.951897

"""
from alembic import op
import sqlalchemy as sa
from flask_appbuilder.models.mixins import FileColumn


# revision identifiers, used by Alembic.
revision = 'befea11f8642'
down_revision = '24d769a75e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('dataset', sa.Column('dataset_file', flask_appbuilder.models.mixins.FileColumn(), nullable=False))
    op.add_column('dataset', sa.Column('dataset_file',  FileColumn(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'dataset_file')
    # ### end Alembic commands ###
