"""empty message

Revision ID: eabb5e41bc35
Revises: 917384921e87
Create Date: 2022-11-15 06:34:22.565514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eabb5e41bc35'
down_revision = '917384921e87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_attribute')
    op.drop_table('lyctest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lyctest',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('test_name', mysql.VARCHAR(length=255), server_default=sa.text("'12345'"), nullable=True),
    sa.Column('test_num', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('des', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    comment='lyc_test_table',
    mysql_comment='lyc_test_table',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user_attribute',
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.Column('changed_on', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_by_fk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('changed_by_fk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], name='user_attribute_ibfk_1'),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], name='user_attribute_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], name='user_attribute_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
