"""empty message

Revision ID: fb0c39ae5cd9
Revises: 1540a12d86c3
Create Date: 2022-12-07 02:41:36.500464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0c39ae5cd9'
down_revision = '1540a12d86c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('dataset_file', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'dataset_file')
    # ### end Alembic commands ###
